FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]

# FROM node:18-alpine as build
# WORKDIR /app
# COPY public/ /react-docker-example/public
# COPY src/ /app/src
# COPY package.json /app
# RUN npm install
# CMD ["npm", "start"]

# FROM nginx:1.19.0
# WORKDIR /use/share/nginx/html
# RUN rm -rf ./*
# copy --from=build /app/build .
# ENTRYPOINT ["nginx", "-g", "daemon off;"]