FROM openjdk:11

RUN apt-get update && apt-get install -y curl unzip python3 python3-pip
COPY dependency-check-8.4.0-release.zip .
RUN unzip dependency-check-8.4.0-release.zip

COPY requirements.txt /python-utility/
WORKDIR /python-utility
RUN pip3 install -r requirements.txt

COPY dependency-check.py /python-utility/

WORKDIR /dependency-check

ENTRYPOINT ["./bin/dependency-check.sh"]
